# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "gcc", "gdal", "geos", "proj"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --chdir src/Mapas app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
