# Railway configuration for Backend
# This file should ONLY be used by the atu-traffic-pulse service

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "gunicorn --chdir src/Mapas app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
