[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "gunicorn --chdir src/Mapas app:app --bind 0.0.0.0:5000 --workers 1 --timeout 120 --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10