# Railway configuration for Backend ONLY# Railway configuration

# Place this file in the root of your project# This tells Railway to use Dockerfile for builds

# Railway will use this for the backend service

[build]

[build]builder = "dockerfile"

builder = "dockerfile"dockerfilePath = "Dockerfile.backend"

dockerfilePath = "Dockerfile.backend"

[deploy]

[deploy]startCommand = "gunicorn --chdir src/Mapas app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"

startCommand = "gunicorn --chdir src/Mapas app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"restartPolicyType = "ON_FAILURE"

restartPolicyType = "ON_FAILURE"restartPolicyMaxRetries = 10

restartPolicyMaxRetries = 10
