# Railway configuration for Frontend
# This tells Railway to use Dockerfile.frontend

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.frontend"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
