services:
  # Frontend - React + Vite
  - type: web
    name: atu-traffic-pulse-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://atu-traffic-pulse-backend.onrender.com
    healthCheckPath: /

  # Backend - Python Flask (Mapas)
  - type: web
    name: atu-traffic-pulse-backend
    runtime: python
    plan: free
    # ✅ FIX 1: Instalar requirements desde la raíz correcta
    buildCommand: |
      pip install --upgrade pip
      cd src/Mapas && pip install -r requirements.txt
    
    # ✅ FIX 2: Usar el worker correcto y desde el directorio correcto
    # Gunicorn necesita estar en el mismo directorio que app.py
    startCommand: cd src/Mapas && gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --worker-class gthread --timeout 300 --keep-alive 75 --log-level info --access-logfile - --error-logfile - app:app
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      # ✅ FIX 3: No sobrescribir PORT, Render lo maneja automáticamente
      # - key: PORT
      #   value: 5000  <- ESTO CAUSA CONFLICTOS
      
      # ✅ FIX 4: Variables críticas para Python
      - key: PYTHONUNBUFFERED
        value: "1"
      
      # ✅ FIX 5: Desactivar cache de Python bytecode
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    
    healthCheckPath: /health
    
    # ✅ FIX 6: CRÍTICO - Persistir el directorio de caché
    # Sin esto, los archivos de caché se pierden en cada deploy
    disk:
      name: cache-storage
      mountPath: /opt/render/project/src/Mapas/cache
      sizeGB: 1