services:
  # Frontend - React + Vite
  - type: web
    name: atu-traffic-pulse-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://atu-traffic-pulse-backend.onrender.com
    healthCheckPath: /

  # Backend - Python Flask (Mapas)
  - type: web
    name: atu-traffic-pulse-backend
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    # Usar gunicorn para producción (más estable que python app.py)
    startCommand: cd src/Mapas && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
